```{r}
library(readr)
library(tidyverse)
```


```{r}
egresos <- read_csv("data/tb_egreso_dm.csv")
View(egresos)
```


```{r}
distinct(egresos, Parametro)
```


```{r}
poblacion <- read_csv("data/tb_poblacion.csv")
  poblacion_totales <- poblacion %>%
    filter(Sexo == 0) %>%
    group_by(Anio, Cve_Presupuestal, Nombre_Unidad)%>%
    summarise(Totales_Poblacion = sum(Poblacion, na.rm = TRUE), .groups = 'drop') %>%
    mutate(Cve_Presupuestal = as.character(Cve_Presupuestal))
    names(poblacion_totales) <- tolower(names(poblacion_totales))

egresos %>%
    filter(Sexo == 0, Parametro == "Egresos_DM") %>%
    group_by(Anio, Nombre_OOAD, Nombre_Unidad, Cve_Presupuestal) %>%
    summarise(Dato = sum(Dato, na.rm = TRUE),.groups = 'drop') %>%
    rename(anio = Anio, cve_presupuestal = Cve_Presupuestal) %>%
    left_join(poblacion_totales, by = c("anio", "cve_presupuestal")) %>%
    mutate(Dato2 = Dato/totales_poblacion*100000) %>%
    select(Anio = anio,Nombre_OOAD, Nombre_Unidad, Dato, totales_poblacion, Dato2)
```



```{r}
data <- read_csv("data/tb_consulta_DM.csv")
    data %>% 
      filter (Parametro == 'Consulta_MF', Sexo == 0) %>%
      group_by(Anio, Nombre_OOAD, Nombre_Unidad, Cve_Presupuestal) %>%
      summarise(Dato = sum(Dato, na.rm = TRUE), .groups = 'drop') %>%
      rename(anio = Anio, cve_presupuestal = Cve_Presupuestal) %>%
      left_join(poblacion_totales, by = c("anio", "cve_presupuestal")) %>%
      mutate(Dato2 = Dato/totales_poblacion*1000) %>%
      select(Anio = anio,Nombre_OOAD, Nombre_Unidad, Dato, totales_poblacion, Dato2)
```


```{r}
indicadores <- read_csv("data/tb_datos_historico_indicadores.csv")
View(indicadores)

indicadores %>%
    filter(anio == 2014, tipo == "Unidad", nom_indicador == "DM 03") %>%
    mutate(
      Valor_Indicador = indicador,
      Mes = factor(mes_i, levels = 1:12, labels = month.abb)
    ) %>%
    select(
      Mes,
      Indicador = nom_indicador,
      Numerador = numerador,
      Denominador = denominador,
      Valor_Indicador
    ) %>%
    arrange(Mes)
```