------------------------------------------------------------------------

------------------------------------------------------------------------

```{r}
library(readr)
files <- list.files(path = "data/", pattern = "*.csv", full.names = TRUE)
for(file in files){
  assign(gsub("data/|\\.csv", "", file), read_csv(file))
}
```

```{r}
# global.R

library(DBI)
library(odbc)

# Connection string to establish a connection to the SQL Server database
connection_details <- dbConnect(odbc::odbc(), 
                                Driver = "SQL Server", 
                                Server = "MTO02438WSCHG7", 
                                Database = "DAS_DM", 
                                Trusted_Connection = "Yes")

# Function to load data from the database
load_data <- function(query) {
  data <- dbGetQuery(connection_details, query)
  return(data)
}

# Example of loading specific tables
 censo <- load_data("SELECT * FROM dbo.tb_censo_DM")
 consultas <- load_data("SELECT * FROM tb_consulta_dm")
 indicadores <- load_data("SELECT * FROM dbo.tb_datos_historico_indicadores")
 incapacidades <- load_data("SELECT * FROM dbo.tb_dm_incap")
 poblacion <- load_data("SELECT * FROM dbo.tb_poblacion")
 egresos <- load_data("SELECT * FROM dbo.tb_egreso_dm")

```

```{r}
library(dplyr)
# Filter 'censo' for 'Sexo' = 0 and group by 'Nombre_Unidad' and 'Anio'
# Then, summarise to get the annual totals for 'Pacientes_DM' and 'PAMF'
totales_anuales <- censo %>%
  filter(Sexo == 0) %>%
  group_by(Nombre_OOAD, Nombre_Unidad, Anio) %>%
  summarise(Pacientes_DM = sum(Pacientes_DM), PAMF = sum(PAMF), Prevalencia_DM_porc = Pacientes_DM/PAMF*100)
```


```{r}

```